apiVersion: 0.1.0
environments:
  default:
    destination:
      namespace: default
      server: https://1.2.3.4
    k8sVersion: v1.10.0
    path: default
kind: ksonnet.io/app
name: configmap-importfile
version: 0.0.1
