apiVersion: 0.1.0
environments:
  prod:
    destination:
      namespace: default
      server: https://prod.com
    k8sVersion: v1.9.4
    path: prod
  qa:
    destination:
      namespace: default
      server: https://qa.com
    k8sVersion: v1.9.4
    path: qa
kind: ksonnet.io/app
name: ks-stackframe-bug
registries:
  incubator:
    gitVersion:
      commitSha: 40285d8a14f1ac5787e405e1023cf0c07f6aa28c
      refSpec: master
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
